 "use client";
import Image from "next/image";import{useEffect,useState}from"react";
const skills=["Node.js","Express.js","MongoDB","REST APIs","Socket.IO","Next.js","Firebase","Vercel","HTML","C","Figma","GitHub"];
const shots=[["campus-01.png","Profile & privacy settings"],["campus-02.png","Real-time group chat"],["campus-03.png","Notifications"],["campus-04.png","Campus Connect splash screen"],["campus-05.png","Group messages"],["campus-06.png","Campus feed"],["campus-07.png","Authentication"],["campus-08.png","Student profile"]];
export default function Home(){const[menu,setMenu]=useState(false),[active,setActive]=useState<number|null>(null);useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==="Escape"&&setActive(null);addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[]);
return <main><nav className="nav"><a className="logo" href="#home"><span>M</span> Meet Dholu</a><button className="menu" aria-label="menu" onClick={()=>setMenu(!menu)}>☰</button><div className={"navlinks "+(menu?"show":"")}>{["about","skills","project","education","contact"].map(x=><a key={x} href={"#"+x} onClick={()=>setMenu(false)}>{x}</a>)}<a className="navcta" href="#contact">Let's talk ↗</a></div></nav>
<section id="home" className="hero wrap"><div><div className="eyebrow"><i/> Available for fresher / full-time opportunities</div><h1>Backend logic.<br/><em>Real-world</em> products.</h1><p className="heroText">I’m Meet Dholu — a BCA graduate building my career in backend and full-stack development. I enjoy APIs, databases, authentication and real-time applications.</p><div className="buttons"><a className="btn dark" href="#project">Explore my work</a><a className="btn" href="#contact">Get in touch</a></div><div className="miniStats"><div><b>01</b><span>Featured project</span></div><div><b>2026</b><span>BCA graduate</span></div><div><b>2</b><span>Team members</span></div></div></div>
<div className="heroArt"><div className="orb o1"/><div className="orb o2"/><div className="orb o3"/><div className="terminal"><div className="termTop"><span/><span/><span/><label>meet@portfolio:~</label></div><pre><em>const</em> developer = {"{"}
  name: <strong>"Meet Dholu"</strong>,
  role: <strong>"Backend Developer"</strong>,
  stack: [<strong>"Node.js"</strong>, <strong>"MongoDB"</strong>, <strong>"REST APIs"</strong>],
  status: <strong>"open_to_work"</strong>
{"}"};</pre><div className="cursor">▌</div></div><div className="floatCard c1">⌘ REST APIs</div><div className="floatCard c2">◈ MongoDB</div><div className="floatCard c3">↯ Socket.IO</div></div></section>
<section id="about" className="wrap section lineTop"><div className="label">01 — About</div><div className="two"><h2>I like building the part users don’t see.</h2><div className="body"><p>I’m a recent BCA graduate from <b>Sanskar Institute of Management and Information Technology</b>, affiliated with Kachchh University.</p><p>My strongest interest is backend development. I like understanding how data moves through an application, how APIs are designed, how authentication works and how real-time features stay reliable.</p><p>Campus Connect gave me practical experience working on a real multi-feature social application with another developer.</p></div></div></section>
<section id="skills" className="wrap section"><div className="head"><div><div className="label">02 — Skills</div><h2>My current toolkit.</h2></div><p>Focused on backend fundamentals, practical APIs and full-stack growth.</p></div><div className="skillGrid">{skills.map((s,i)=><div className="skill" key={s}><span>{String(i+1).padStart(2,"0")}</span><b>{s}</b></div>)}</div></section>
<section id="project" className="wrap section lineTop"><div className="head"><div><div className="label">03 — Featured project</div><h2>Campus Connect<span>.</span></h2></div><div className="tag">College Social Network</div></div><div className="intro"><div><p className="big">A private social media platform created specifically for college students — with student-only registration, posts, stories, groups, chat, events, announcements and moderation.</p><div className="roles"><div><small>MY ROLE</small><b>Backend + Database</b></div><div><small>TEAM</small><b>2 members</b></div><div><small>FRONTEND</small><b>Flutter by teammate</b></div></div></div><div className="stack"><small>CORE STACK</small><div>{["Next.js","Express.js","MongoDB","REST APIs","Socket.IO","Firebase","Vercel"].map(x=><i key={x}>{x}</i>)}</div></div></div>
<div className="features"><div><span>01</span><section><h3>Student verification</h3><p>Only approved college email formats can register. Students verify their account using an OTP sent to their college email.</p></section></div><div><span>02</span><section><h3>API + database architecture</h3><p>Created REST API routes/controllers and MongoDB collections for users, posts, comments, groups, messages, stories, events, notifications, reports and more.</p></section></div><div><span>03</span><section><h3>Real-time + notifications</h3><p>Implemented real-time group communication with Socket.IO and integrated Firebase for notifications.</p></section></div><div><span>04</span><section><h3>Admin moderation</h3><p>Built backend support for reporting, blocking and admin actions so unwanted student activity can be reviewed and controlled.</p></section></div></div>
<div className="gallery">{shots.map((s,i)=><button className="shot" key={s[0]} onClick={()=>setActive(i)}><Image src={"/project/"+s[0]} alt={s[1]} fill sizes="(max-width:700px) 100vw,25vw"/><span>{s[1]}</span></button>)}</div><div className="projectFoot"><p><b>My backend contribution:</b> OTP verification · authentication · JWT/session handling · MongoDB · REST APIs · CRUD · Socket.IO · Firebase notifications · reports · admin moderation.</p><div className="buttons"><a className="btn dark" href="https://github.com/meet-dholu/campus-connect" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a className="btn" href="https://campus-connect-demo.vercel.app" target="_blank" rel="noopener noreferrer">Live demo ↗</a></div></div></section>
<section id="education" className="wrap section"><div className="label">04 — Education</div><div className="edu"><div className="date">JUL 2023<br/>↓<br/>APR 2026</div><div><small>BACHELOR OF COMPUTER APPLICATIONS</small><h2>Sanskar Institute of Management and Information Technology</h2><p>Under Kachchh University</p></div><div className="score"><b>63%</b><span>Overall</span></div></div></section>
<section id="contact" className="wrap section contact lineTop"><div><div className="label">05 — Contact</div><h2>Ready for the<br/><em>next opportunity.</em></h2><p>I’m looking for a fresher/full-time role where I can grow as a backend or full-stack developer and contribute to real software.</p></div><div className="contactList"><a href="mailto:meet.dholu@example.com"><span>EMAIL</span><b>meet.dholu@example.com ↗</b></a><a href="https://github.com/meet-dholu" target="_blank" rel="noopener noreferrer"><span>GITHUB</span><b>github.com/meet-dholu ↗</b></a><a href="https://www.linkedin.com/in/meet-dholu" target="_blank" rel="noopener noreferrer"><span>LINKEDIN</span><b>linkedin.com/in/meet-dholu ↗</b></a></div></section>
<footer className="wrap"><span>© 2026 Meet Dholu</span><span>Backend · Full-Stack · Always learning</span></footer>
{active!==null&&<div className="modal" onClick={()=>setActive(null)}><button aria-label="close">×</button><div className="modalImg" onClick={e=>e.stopPropagation()}><Image src={"/project/"+shots[active][0]} alt={shots[active][1]} fill sizes="90vw"/><p>{shots[active][1]}</p></div></div>}</main>}